---
- name: CloudEngine facts test
  hosts: all
  connection: local
  gather_facts: false
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      port: "{{ ansible_ssh_port }}"
      username: "{{ username }}"
      password: "{{ password }}"
      transport: cli
      community.network.ce_facts:
        gather_subset: all
        provider: "{{ cli }}"
  tasks:

...
